export const GET_INGREDIENTS_LIB_REQUEST = 'GET_INGREDIENTS_LIB_REQUEST';
export const GET_INGREDIENTS_LIB_SUCCESS = 'GET_INGREDIENTS_LIB_SUCCESS';
export const GET_INGREDIENTS_LIB_ERROR = 'GET_INGREDIENTS_LIB_ERROR';