export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST';
export const PLACE_ORDER_ERROR = 'PLACE_ORDER_ERROR';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';

export const SET_ORDER_DETAIL = 'SET_ORDER_DETAIL';